### ISSUE TITLE
Question: calling functions with iterators as parameters

### ISSUE THREAD

**Issue by bsdz** [ryanhaining/cppitertools#102]
Is there a recommended way to pass the iterators as parameters to functions? For example in the snippet below I'm passing myIter via template parameter although I feel it needs some constraints here; or, perhaps there's a smarter runtime way to do it?

```c++
using MyMap = map<string, variant<double, int>>;
auto pred = [](auto x) { return std::get<0>(x) > std::get<1>(x); };
auto toMap = [](auto x) -> MyMap {
    MyMap map;
    map.insert({"n"s, std::get<0>(x)});
    map.insert({"m"s, std::get<1>(x)});
    return map;
};

// is their a runtime type I can use instead of a template?
// if I used a template, can I apply any constraints/concepts?
template <typename T>
void printIter(T &x) {
    for (auto b : x) std::cout << b << '\n';
}

void foo() {
    std::vector<int> seq1{20, 30, 40, 50};
    std::vector<int> seq2{5, 10, 15, 20};

    auto myIter =
        iter::product(seq1, seq2) | iter::filter(pred) | iter::imap(toMap);

    printIter(myIter);
}
```

**Comment by ryanhaining** [comment]
what you have is what I would recommend. As far as a concept, I expected `std::ranges::range` to work but I'm getting an issue down the stack that isn't obvious to me.

**Comment by bsdz** [comment]
Thanks for confirming. The template functions work for me (although it does mean I have to put the code in my header files as the type structures generated are quite varied). I can live without the concepts. Thanks again :)
