### ISSUE TITLE
sorted: can modify elements - why normal?

### ISSUE THREAD

**Issue by hoxnox** [ryanhaining/cppitertools#27]
Hi. I don't understand the code in the test/test_sorted.cpp:

```
  std::vector<int> ns(3, 9);
  for (auto&& n : sorted(ns)) {
    n = -1;
  }
  Vec vc(3, -1);
  REQUIRE(ns == vc);
```

Why so? Doesn't vc must be (-1, -1)? Can you explain?

**Comment by ryanhaining** [comment]
In both cases its _not_ using the initializer list constructor so you have
ns = {9,9,9} and vc = {-1,-1,-1}. The loop sets each element in ns to -1.

**Comment by hoxnox** [comment]
=) Sorry. Not square braces. Of corse...
