### ISSUE TITLE
Uses features from C++14

### ISSUE THREAD

**Issue by ehein6** [ryanhaining/cppitertools#29]
`iterbase.hpp` uses [`std::enable_if_t`](http://en.cppreference.com/w/cpp/types/enable_if), which was not added until C++14. The repository description indicates that this is a C++11 library, and nowhere in the readme does it mention that C++14 support is required.

**Comment by ehein6** [comment]
Sorry for not searching earlier, I see that the C++11/14 issue has been mentioned in some closed issues. I guess I'd just like to see the documentation updated.

**Comment by ryanhaining** [comment]
Sorry about the description, I forgot to update that when I updated the master branch to c++14.
If you need C++11 you can use the last tagged release: https://github.com/ryanhaining/cppitertools/releases/tag/v0.1

**Comment by ehein6** [comment]
Thanks!
