### ISSUE TITLE
[c++17] enumerate should work with structured bindings

### ISSUE THREAD

**Issue by ryanhaining** [ryanhaining/cppitertools#33]
Currently this is invalid with c++17

```c++
for (auto&& [i, e] : iter::enumerate(seq)) {
    // ...
}
```
because the object returned by enumerate's iterator's `operator*` is a subclass of pair with more data members. In some way, the above should work.

**Comment by dnbh** [comment]
Maybe add a plainer iteration type which with an operator implicit type conversion which strips out the extra metadata?

**Comment by ryanhaining** [comment]
I was thinking of providing `get` for the yielded type. If I don't care about compatibility I could have it yield `pair`, which I should've done in the first place, seems a little late for that change now though.

**Comment by ryanhaining** [comment]
Turns out all I needed was `tuple_size` and `tuple_element`. `std::get(std::pair)` took care of the rest.
