### ISSUE TITLE
Can't chain a `std::set` with an `std::vector`

### ISSUE THREAD

**Issue by graipher** [ryanhaining/cppitertools#35]
This simple example fails to compile:

```{c++}
#include <stdlib.h>
#include "cppitertools/chain.hpp"

std::vector<const char *> c1 = {"a", "b", "c"};
std::set<const char *> c2 = {"d", "d", "e"};
for (auto n : iter::chain(c1, c2))
{
    std::cout << n << std::endl;
}
```

The following errors are raised:

```
in instantiation of function template specialization 'iter::impl::ChainMaker::operator()<std::vector<const char *,
      std::allocator<const char *> > &, std::set<const char *, std::less<const char *>, std::allocator<const char *> >
      &>' requested here
for (auto n : iter::chain(c1, c2)) {std::cout << n << std::endl;}
                         ^
```

**Comment by ryanhaining** [comment]
The problem is described in the static_assert
```
static assertion failed: All chained iterables must have iterators that dereference to the same type, including cv-qualifiers and references.
```
Since `std::set` iterators provide const references, and `std::vector`'s do not, there is a mismatch between the two. 

Your example can be made to work by getting a const reference to `c1` either by `static_cast`ing

```c++
for (auto n : iter::chain(static_cast<const std::vector<const char*>&>(c1), c2))
```
or creating an intermediate const reference to `c1`
```c++
const auto& c1_ref = c1;
for (auto n : iter::chain(c1_ref, c2))
```

anything that makes the vector iterator dereference to a const reference

**Comment by graipher** [comment]
Thanks for the comment. I thought it was related to the caveat, but knew too little to know exactly what it meant. With the work-around you supplied, it indeed works

**Comment by ryanhaining** [comment]
Cool, glad to help. thanks for your interest

**Comment by ryanhaining** [comment]
A final note, with the c++17 stdlib you will be able to do this with a call to [std::as_const](http://en.cppreference.com/w/cpp/utility/as_const)

    for (auto n : iter::chain(std::_const(c1), c2))
