### ISSUE TITLE
count is not actually infinite

### ISSUE THREAD

**Issue by furkanusta** [ryanhaining/cppitertools#42]
This is just a little nitpick, but I was reading you code base and realized that iter::count is doing limit checking and the explanation is a bit off
> Effectively a range without a stopping point. 

Although in signed integers overflow is undefined, it is defined in unsigned integers as wraparound but the below loop ends at 65534. (One before the limit)
```
using T = unsigned short;
    for(auto i : iter::count(T{})) {
        if(cond)
            break;
    }
```

I think more reasonable behaviour is just incrementing the counter by step at each iteration without doing a boundary check and let it fail if it ever hits an undefined behaviour. In here you are basically defining the behaviour.

However as I said at the beginning, this is just a little nitpick regarding the documentation and it would be still fine to keep the behaviour as it is but with proper explanation in the documentation.

**Comment by ryanhaining** [comment]
updated description. The previous *Technical Limitation* note was for an old implementation
