### ISSUE TITLE
Product begin won't compile

### ISSUE THREAD

**Issue by nvhuynh16** [ryanhaining/cppitertools#43]
I was able to get the begin iterator for range to work:
```
auto r = iter::range(5);
auto first = r.begin();
```

But I can't get product to compile:
```
std::string s = "abc";
auto p = iter::product(s,s);
auto first = p.begin();
```

This was compiled on Visual Studio 2017.
Here's the error message:

> 1>main.cpp
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(75): error C2672: 'iter::impl::get_iters::get_begin': no matching overloaded function found
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(85): note: see reference to alias template instantiation 'iterator_type<unknown-type>' being compiled
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(39): note: see reference to alias template instantiation 'iterator_deref<unknown-type>' being compiled
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(54): note: see reference to alias template instantiation 'ProdIterDeref<std::basic_string<char,std::char_traits<char>,std::allocator<char>>&>' being compiled
> 1>d:\visual studio 2017\itertools_test\product_test\product_test\main.cpp(18): note: see reference to class template instantiation 'iter::impl::Productor<std::string &,std::string &>::IteratorTempl<Container,iter::impl::Productor<std::string &>::IteratorTempl<Container,iter::impl::Productor<>::Iterator>>' being compiled
> 1>        with
> 1>        [
> 1>            Container=std::string &
> 1>        ]
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(75): error C2893: Failed to specialize function template 'unknown-type iter::impl::get_iters::get_begin(T &)'
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(75): note: With the following template arguments:
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(75): note: 'T=add_rvalue_reference<_Ty>::type'
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(85): error C2672: 'std::declval': no matching overloaded function found
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(85): error C2893: Failed to specialize function template 'add_rvalue_reference<_Ty>::type std::declval(void) noexcept'
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(85): note: With the following template arguments:
> 1>d:\visual studio 2017\itertools_test\cppitertools\internal\iterbase.hpp(85): note: '_Ty=unknown-type &'
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(39): error C3546: '...': there are no parameter packs available to expand
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(54): error C3203: 'tuple': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(58): error C2512: 'std::is_same<unknown-type,unknown-type>': no appropriate default constructor available
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(58): note: The target type has no constructors
> 1>d:\visual studio 2017\itertools_test\cppitertools\product.hpp(108): error C3203: 'tuple': unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type

**Comment by ryanhaining** [comment]
I am confused by most of these errors, but the more I look at product's `operator->` and `operator*` the more I think it's wrong

**Comment by ryanhaining** [comment]
I believe everything is working on MSVC latest now.
