### ISSUE TITLE
Building and Running tests

### ISSUE THREAD

**Issue by nvander1** [ryanhaining/cppitertools#44]
I'm not sure how to build and test the project. I've managed to build the tests by running ./download_catch.sh and running scons in the test folder. I can run these tests manually, but I'm sure thats not the proper way.

How should the project be built and tested with Bazel and scons?

**Comment by ryanhaining** [comment]
There is one binary produced by `scons` called `test_all` which is the easiest scons method to run the tests from inside the test directory

```
$ scons
$ ./test_all
```

The bazel way to run all of the tests would be (from any directory in the workspace)

```
$ bazel test //test:all
```

There's no need to do both bazel and scons

**Comment by nvander1** [comment]
Ah perfect, thanks! I've just gotten over the cmake learning curve; now I gotta learn some basics for these other systems too, haha!

**Comment by ryanhaining** [comment]
Fortunately scons (especially) and bazel are a lot easier to manage, though
this project's SConstruct and BUILD files are not a very good example of
the standard ways to use them

**Comment by nvander1** [comment]
From what I've seen it seems that scons configs are basically python scripts. So that seems a lot nicer than the messiness that is cmake. Even the official cmake tutorial is several versions behind the latest.

**Comment by ryanhaining** [comment]
That is correct about scons, you can write python right in the config file.
The tutorial for scons is very good at going from basics to a decent
project I'm. I can't speak to cmake
