### ISSUE TITLE
Can't dereference const zip iterator

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [ryanhaining/cppitertools#49]
```c++
#include <vector>

#include "zip.hpp"

int main()
{
    std::vector<int> a(1);

    const auto it = iter::zip(a).begin();
    const auto [v] = *it;

    return v;
}
```

[ilya@ilya-pc cppitertools]$ clang++ const_iter.cpp -I ./ -std=c++17 -fno-permissive
const_iter.cpp:11:22: error: indirection requires pointer operand ('const iter::impl::Zipped<std::tuple<std::vector<int, std::allocator<int> > &>, 0>::Iterator<std::tuple<std::vector<int, std::allocator<int> > &>, iterator_tuple_type, iterator_deref_tuple>' invalid)
    const auto [v] = *it;

Is there a reason for Zipped::Iterator::operator*() not to be const?
https://github.com/ryanhaining/cppitertools/blob/master/zip.hpp#L90

**Comment by ilyalesokhin-starkware** [comment]
The reason I need to dereference a const iterator is that I want to capture the iterator in a lambda and call the lambda after advancing the iterator.

something like:
for (auto&& it = begin; it != end; ++it) {
    tasks_.emplace([this, it]() {
          func(*it);
    }
}

The iterator inside the lambda is const.
I don't want to save a reference to *it because it might be invalid after calling ++it.
and I don't want to copy the *it because it might be a reference to a large object.

Is copying the const iterator and then dereferencing it? a better solution?

**Comment by ryanhaining** [comment]
If you look at [InputIterator](https://en.cppreference.com/w/cpp/named_req/InputIterator) you'll see that operator++ invalidates any other existing iterators, so your concern about saving a reference to `*it` is not alleviated by saving copies of the iterator. If this weren't already a problem I would suggest making the lambda mutable.

```c++
for (auto&& t : iter::zip(a, b, c)) {
  tasks_.emplace([this, t] { func(t); });
}
```

It seems like you're saving these tasks for later, but note that if you wanted to call them eagerly you could do so with `iter::imap(f, a, b, c)`

**Comment by ilyalesokhin-starkware** [comment]
Is there a way to know if I can keep a reference to *it or whether I need to make a copy?

Also, would should I do with this issue? close it? leave it open?

**Comment by ilyalesokhin-starkware** [comment]
Btw, the error message in both gcc and clang is very confusing.

Do you think something can be done about that?
I tried 

> static_assert(false,  "not implement");

But I couldn't compile anything with that. maybe something a bit more clever could generate a compile time error only if the const operator* is actually called.

**Comment by ryanhaining** [comment]
concepts will help with a lot of the issues in c++20 but I don't think this one can be made much better. a static_assert would have to use a dependent expression, something like `static_assert((T*)nullptr, "not implemented")` but there are so many things not implemented in itertools that I'd be adding hundreds of these everywhere and likely cause some compilers to start failing things they shouldn't be :/

**Comment by ilyalesokhin-starkware** [comment]
> if you're zipping up actual containers (like a few vectors, maps, etc) zip will be returning a tuple of references which isn't going to consume much space. I'd be really surprised if this was your bottleneck

You are correct that copying is not an issue when zip is used, because the zip iterator returns a tuple of references.
The problem is that the same same code might cause an expensive copy when standard containers are passed without using zip.

It looks like I need some kind of wrapper for standard collection and iterator that returns an std::reference_wrapper instead of a referece.

Something like:
```
template <class BaseIterator>
class ReferenceWrapperIterator : public BaseIterator {
 public:
  ReferenceWrapperIterator(BaseIterator&& other) : BaseIterator(std::move(other)) {}

  auto operator*() const { return std::ref(this->BaseIterator::operator*()); };
};

template <typename Collection>
class ReferenceWrapped {
 public:
  ReferenceWrapped(Collection& collection) : collection_(collection) {}

  auto begin() { return ReferenceWrapperIterator(collection_.begin()); };
  auto end() { return ReferenceWrapperIterator(collection_.end()); };

 private:
  Collection& collection_;
};
```
And then you can do
```
std::vector<int> v;
for (auto&& t : ReferenceWrapped(v) {
  tasks_.emplace([this] { func(t); });
}
```

Do you know if something like that already exists in cppitertools? or std?

**Comment by ryanhaining** [comment]
Reference wrapper doesn't solve your problem because you're still binding a reference to whatever zip returns. You can't get a reference_wrapper to what zip's iterator is giving you, it's not any safer than a raw reference and `std::ref` won't even compile when I try to do it:

```c++
#include <cppitertools/zip.hpp>
#include <functional>

int main() {
  char v[] = {0};
  auto z = iter::zip(v);
  auto r = std::ref(*z.begin());
}
```

With a gcc saying:

```
zipref.cpp:7:31: error: use of deleted function ‘void std::ref(const _Tp&&) [with _Tp = std::tuple<char&>]’
   auto r = std::ref(*z.begin());
```

So, here is more like a straight forward demonstration of the problem:

```c++
#include <cppitertools/zip.hpp>

#include <iostream>
#include <functional>
#include <tuple>
#include <vector>

template <typename T>
void display_later(const T& seq) {
  std::vector<std::function<void()>> funcs;
  for (auto it = seq.begin(), end = seq.end(); it != end; ++it) {
    // get a reference to what the iterator points to
    auto&& t = *it;
    // hang onto that reference for later
    funcs.emplace_back([&t]  { std::cout << std::get<0>(t) << '\n'; });
  }

  for (auto&& f : funcs) {
    f(); // print get<0> of everything we have references to
  }
}



int main() {
  std::vector v{2, 4, 6};
  display_later(iter::zip(v)); // prints 6 6 6


  std::vector v_tups{std::tuple{2}, std::tuple{4}, std::tuple{6}};
  display_later(v_tups); // prints 2 4 6
}
```

The critical part here is that we have `[&t]` which is fine for the `vector` but for the zipped sequence we really want `[t]` to copy that tuple. Thankfully, we are living in an exciting time to be a c++ programmer. we can modify the loop to do the capture we want based on the type of `t`, add a `#include <type_traits>` at the top, and switch up the inner loop to get this:

```c++
#include <cppitertools/zip.hpp>

#include <iostream>
#include <functional>
#include <tuple>
#include <type_traits> // added this include here
#include <vector>

template <typename T>
void display_later(const T& seq) {
  std::vector<std::function<void()>> funcs;
  for (auto it = seq.begin(), end = seq.end(); it != end; ++it) {
    auto&& t = *it;
    // added the if constexpr here
    if constexpr (std::is_lvalue_reference_v<decltype(t)>) {
      //std::cout << "capture reference\n";
      funcs.emplace_back([&t] { std::cout << std::get<0>(t) << '\n'; });
    } else {
      //std::cout << "capture value\n";
      funcs.emplace_back([t] { std::cout << std::get<0>(t) << '\n'; });
    }
  }

  for (auto&& f : funcs) {
    f();
  }
}



int main() {
  std::vector v{2, 4, 6};
  display_later(iter::zip(v)); // now this prints 2 4 6 as well

  std::vector v_tups{std::tuple{2}, std::tuple{4}, std::tuple{6}};
  display_later(v_tups);
}
```

**Comment by ryanhaining** [comment]
No problem. Good point there, in that case, a bit more complicated but you'd want to check the [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags) and decide based on that. If it's not an `InputIterator` then copy

```c++
#include <cppitertools/zip.hpp>

#include <iostream>
#include <iterator>
#include <functional>
#include <tuple>
#include <type_traits>
#include <vector>

template <typename T>
void display_later(const T& seq) {
  using iter_type = typename std::iterator_traits<std::decay_t<decltype(seq.begin())>>::iterator_category;
  constexpr auto copy_element = std::is_same_v<iter_type, std::input_iterator_tag>;

  std::vector<std::function<void()>> funcs;
  for (auto&& t : seq) {
    if constexpr (copy_element || !std::is_lvalue_reference_v<decltype(t)>) {
      //std::cout << "capture value\n";
      funcs.emplace_back([t] { std::cout << std::get<0>(t) << '\n'; });
    } else {
      //std::cout << "capture reference\n";
      funcs.emplace_back([&t] { std::cout << std::get<0>(t) << '\n'; });
    }
  }

  for (auto&& f : funcs) {
    f();
  }
}



int main() {
  std::vector v{2, 4, 6};
  display_later(iter::zip(v));

  std::vector v_tups{std::tuple{2}, std::tuple{4}, std::tuple{6}};
  display_later(v_tups);
}
```
