### ISSUE TITLE
VS2019 compilation errors iter::chain (fix planned for 16.4)

### ISSUE THREAD

**Issue by tonyriviere88** [ryanhaining/cppitertools#63]
Hello,
few time ago I was trying to compile CppIterTools with VS2019 and I get errors with `iter::chain` with this kind of errors:
```
iterbase.hpp(94,36): error C2672:  'iter::impl::get_iters::get_begin': no matching overloaded function found
iterbase.hpp(94,1): error C2893:  Failed to specialize function template 'unknown-type iter::impl::get_iters::get_begin(T &)'
iterbase.hpp(104,43): error C2672:  'std::declval': no matching overloaded function found
iterbase.hpp(104,1): error C2893:  Failed to specialize function template '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
```
I have filled a bug to Microsoft and they seem to have fix the bug in their compiler on 16.4 version which isn't yet release (maybe a month or 2).
Here is the link:
https://developercommunity.visualstudio.com/content/problem/638663/vs2019-c-failed-to-specialize-sfinae-regression.html

**Comment by ryanhaining** [comment]
I gotta admit, I did not expect msvc to stop working once it started. Thanks for the heads up, I should look into appveyor and see if I can test against msvc 2019 too

**Comment by tonyriviere88** [comment]
I've downloaded the latest preview version VS 2019 16.4 preview 2: the compilation error has been fixed.
