### ISSUE TITLE
errors in iterbase.hpp (unable to build solution).

### ISSUE THREAD

**Issue by imstark** [ryanhaining/cppitertools#64]
![Screenshot (5)](https://user-images.githubusercontent.com/33204350/70309288-3207eb80-1833-11ea-9e51-0e59f09c2f31.png)

errors while building the solution but I can't see any error here.

**Comment by ryanhaining** [comment]
What version of msvc are you using? Is your build configured for C++17?

**Comment by imstark** [comment]
msvc 2019 16. Yes build is configured for c++17
