### ISSUE TITLE
Make available via conan

### ISSUE THREAD

**Issue by bigerl** [ryanhaining/cppitertools#68]
[Conan](https://github.com/conan-io/conan) is besides Microsoft's vcpkg the most popular package manager for C++ out there. But with good support for cmake and linux in contrast to vcpkg.
We use them it in our C++ projects to pull in dependencies without including them into our source code or installing them on the building system. See for example https://bintray.com/stiffstream/public/restinio%3Astiffstream for how libraries are published on conan. 

Would you consider to publish cppitertools on conan? We could help with conanizing cppitertools. 

FYI @Shaheen47

**Comment by ryanhaining** [comment]
If you know what to do to make it work then I have no problems with
integrating it, I can look into bintray in a few days

**Comment by Shaheen47** [comment]
ok we will help with creating the conan recipe for that .

**Comment by jayvdb** [comment]
It is now in ConanCenter https://repology.org/project/cppitertools/versions
I believe this can be closed.

**Comment by bigerl** [comment]
thx :)
