### ISSUE TITLE
The cmake version config file is not installed alongside the config file

### ISSUE THREAD

**Issue by strega-nil** [ryanhaining/cppitertools#72]
According to https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html, the cmake version config file should be installed alongside the cmake config file; however:

```cmake
install(EXPORT cppitertools-targets
        FILE cppitertools-config.cmake
        NAMESPACE cppitertools::
        DESTINATION ${cppitertools_INSTALL_CMAKE_DIR}/cppitertools
        )

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/cppitertools-config-version.cmake DESTINATION ${cppitertools_INSTALL_CMAKE_DIR})
```

is how the version file is installed -- afaict, this is a silent failure to use the version file. It seems that the `DESTINATION` should probably be `${cppitertools_INSTALL_CMAKE_DIR}/cppitertools`, like the `cppitertools-config.cmake` file.

**Comment by ryanhaining** [comment]
I actually do not know how to use cmake, another contributor was kind enough to create the cmake config for the project. Would you be willing to submit a pull request for the proposed fix? If not I can try to figure it out.

**Comment by strega-nil** [comment]
Yeah, absolutely.

**Comment by strega-nil** [comment]
@ryanhaining how much do you care about backwards-compatibility? The current defaults are really incorrect for how cmake should work; can we change them? I can just fix the issue in as backwards-compatible a way as possible, or I can fix the issue in a non-back-compat way which will make new users happier.

**Comment by ryanhaining** [comment]
As long as it works on appveyor I'm not really concerned with breaking others if you can provide some instruction here on what someone might have to fix if broken. I appreciate the attention to detail

**Comment by strega-nil** [comment]
Alright, cool :)
