### ISSUE TITLE
Bad check in CMakeLists

### ISSUE THREAD

**Issue by GabrielRavier** [ryanhaining/cppitertools#76]
https://github.com/ryanhaining/cppitertools/blob/539a5be8359c4330b3f88ed1821f32bb5c89f5f6/CMakeLists.txt#L4-L19

There are two problems with this :
1. It is advised to set a Cache variable, but an env variable is checked instead
2. The warning is pointless as CMake will find that config in either directory, so it doesn't matter that it has been changed

**Comment by ryanhaining** [comment]
@strega-nil for input

**Comment by strega-nil** [comment]
@GabrielRavier yeah, I meant to check `CACHE{...}` I think... I just wrote a bug. However, the reason I wrote that warning is because it's technically a visible change, if someone was depending on it being in `share/cppitertools/cmake`.
