### ISSUE TITLE
enumerate with signed index

### ISSUE THREAD

**Issue by hmoffatt** [ryanhaining/cppitertools#84]
Would it be possible to have a version of enumerate with a signed index (ie int), or a way to specify the type?

The Qt containers unfortunately use an int for an index rather than std::size_t, so while I can enumerate a Qt container just fine the index type is wrong for then passing to Qt container methods.

Looking at the code I see the index type is templated everywhere, except that EnumerateFn binds it to std::size_t, and EnumerateFn is a friend of iter::impl::Enumerable so it isn't possible to define my own EnumerateFn without modifying enumerate.hpp.

**Comment by ryanhaining** [comment]
The counter's type is inferred, but defaults to `std::size_t` when you don't pass it one. I believe the easiest way to get what you want is to pass integer `0` for the initial counter value as in `iter::enumerate(qt_container, 0)`

```
#include "cppitertools/enumerate.hpp"
#include <iostream>
#include <string>
#include <type_traits>

int main() {
  std::string s{"hello"};
  for (auto [i, c] : iter::enumerate(s, 0)) {
    static_assert(std::is_same_v<std::decay_t<decltype(i)>, int>);
    std::cout << i << " = " << c << '\n';
  }
}
```
