### ISSUE TITLE
Requesting rbegin and rend for iter::repeat

### ISSUE THREAD

**Issue by roastduck** [ryanhaining/cppitertools#86]
Hi there,

It would be better for me to have `rbegin` and `rend` for `iter::repeat`, so I can pass an `iter::repeat` object to `iter::reversed`, and it is trivial to implement.

Thanks

**Comment by ryanhaining** [comment]
Yep, easy, done.

**Comment by roastduck** [comment]
Thank you but it seems you only changed `RepeaterWithCount` but forgot `Repeater`.

**Comment by ryanhaining** [comment]
Ok, done for real this time (I think)

**Comment by ryanhaining** [comment]
I am curious why you'd be passing a `repeat` object to `reversed`. I'm guessing there's just a function that accepts a generic iterable and reverses it?

**Comment by roastduck** [comment]
Thank you for the enhancement.

Yes, my function, where I use `iter::reversed`, accepts generic iterables, but I only pass `std::vector` and `iter::repeat` to it for now (actually, this function implements a "broadcasting" semantic by combining `std::vector` and `iter::repeat`).

Surely it is better to have all iterables supporting `rbegin` and `rend`, but it may require a lot of work, and I found it has already been discussed in #40.
