### ISSUE TITLE
Can't use as subproject

### ISSUE THREAD

**Issue by Naville** [ryanhaining/cppitertools#95]
```
add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/vendor/cppitertools ${CMAKE_CURRENT_BINARY_DIR}/cppitertools/)
target_link_libraries(MyTOOL PUBLIC cppitertools)
```

Results in :

```
CMake Error in cmake/modules/CMakeLists.txt:
  export called with target "MyTOOL" which requires target "cppitertools"
  that is not in any export set.
```

**Comment by ryanhaining** [comment]
I actually have never maintained cmake files myself, they are community contributed. Do you happen know anything about this error?

**Comment by Naville** [comment]
Yeah you need a install/export combination so the parent project can see the target

**Comment by ryanhaining** [comment]
If you know what to write and want to send a pr I will add it. If I knew anything about CMake I would try, but I only really maintain scons and bazel builds.
