### ISSUE TITLE
Combinations seems not to work with std::vector<torch::Tensor> with degree 3.

### ISSUE THREAD

**Issue by Piotr321123** [ryanhaining/cppitertools#99]
Hi, I think I either found a bug or there is missunderstanding of how combinations should works like. There is code sample

```
void run_combinations(int degree, std::vector<torch::Tensor> tensors)
{
    std::cout << "run_combinations with degree: " << degree << "\n";
    std::cout << "combinations" << "\n";
    for ( auto && combination : iter::combinations( tensors, degree ) )
    {
        std::cout << "combination.size() : " << combination.size() << "\n";
        for ( auto && element : combination )
        {
            (void)element;
           //std::cout << "element : " << element << "\n";
        }
    }
    std::cout << "combinations_with_replacement" << "\n";
    for ( auto && combinations_with_replacement : iter::combinations_with_replacement( tensors, degree ) )
    {
        std::cout << "combinations_with_replacement.size() : " << combinations_with_replacement.size() << "\n";
        for ( auto && element : combinations_with_replacement )
        {
            (void)element;
            //std::cout << "element : " << element << "\n";
        }
    }
}

auto tensor =  torch::tensor({{1, 2}, {3, 4}}, torch::kInt32);

std::vector<torch::Tensor> vec;
auto size = tensor.sizes().size() ;
for(std::size_t i =0; i< size; i++)
{
    vec.push_back(tensor[i]);
}
run_combinations(2, vec);
run_combinations(3, vec);
```
    
    
And the output is
 

> run_combinations with degree: 2         
> combinations                            
> combination.size() : 2                                                                                   
> combinations_with_replacement                                                                            
> combinations_with_replacement.size() : 2
> combinations_with_replacement.size() : 2   
> combinations_with_replacement.size() : 2                                                                 
> run_combinations with degree: 3                                                                          
> combinations
> combinations_with_replacement
> combinations_with_replacement.size() : 3
> combinations_with_replacement.size() : 3
> combinations_with_replacement.size() : 3
> combinations_with_replacement.size() : 3

could you tell me why for degree 3 the output is empty for function combinations?
It should print something, right ?

**Comment by ryanhaining** [comment]
You're asking for combinations of size 3 but only giving it an iterable with two elements. What do you expect the output to be?

The output matches python's `itertools.combinations` which [specifies in the docs](https://docs.python.org/3/library/itertools.html#itertools.combinations)

> The number of items returned is  [...] zero when r > n.

r being your `degrees` and `n` being the size of the iterable

`
>>> import itertools
>>> list(itertools.combinations([(1, 2), (3, 4)], 3))
[]
```

**Comment by Piotr321123** [comment]
Hello, thanks for answer! I must have missed that description somehow
